<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>modest</string>
	</array>
	<key>name</key>
	<string>Modest</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>declaration</string>
			<key>match</key>
			<string>\b(action|exception)\b</string>
			<key>name</key>
			<string>keyword.source.dcl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable declaration</string>
			<key>include</key>
			<string>#typelist</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(process)\s*([A-Za-z0-9_]+)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.process</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>process declaration</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>process</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#typelist</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#actions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>actions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>({=)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(=})</string>
					<key>name</key>
					<string>updates</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>::</string>
					<key>name</key>
					<string>keyword.source.modest</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bstop|abort|break\b</string>
					<key>name</key>
					<string>support.function.modest.action</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bwhen|alt|do|par|throw|try|catch|relabel|by|extend|hide|if|else|while|process\b</string>
					<key>name</key>
					<string>keyword.source.control.modest</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btau\b</string>
					<key>name</key>
					<string>constant.language.modest</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Not documented at all, so let's see...</string>
					<key>match</key>
					<string>[=\+\-\*/&lt;&gt;!]=?</string>
					<key>name</key>
					<string>keyword.source.operators.modest</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+(\.\d+)?|true|false\b</string>
					<key>name</key>
					<string>constant.numeric.literal</string>
				</dict>
			</array>
		</dict>
		<key>typelist</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.source.dots</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\((\d+)\s*(\.\.)\s*(\d+)\)</string>
					<key>name</key>
					<string>constant.numeric.modest</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bint|bool|real\b</string>
					<key>name</key>
					<string>storage.type.modest</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.modest</string>
	<key>uuid</key>
	<string>ea086210-cd15-4bdd-bb68-00d06438e277</string>
</dict>
</plist>
